# Generated by Django 2.1.4 on 2018-12-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name_plural': 'hobbies'},
        ),
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigaapp.Hobby'),
        ),
    ]
